language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:test:prepare --trace
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database my_app_test' -U postgres
bundler_args: --binstubs=./bundler_stubs
